# dvc.yaml
stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/diabetes.csv
    outs:
      - models/model.pkl
      - mlruns/
      - metrics.json

  validate:
    cmd: python src/validate.py
    deps:
      - src/validate.py
      - models/model.pkl
      - data/diabetes.csv