# dvc.yaml
stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/dataset.csv
    outs:
      - models/model.pkl
      - mlruns/
    metrics:
      - metrics.json:
          cache: false

  validate:
    cmd: python src/validate.py
    deps:
      - src/validate.py
      - models/model.pkl
      - data/dataset.csv